// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package review

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
	api "github.com/yzc/orange-review/app/review_server/kitex_gen/api"
	base "github.com/yzc/orange-review/app/review_server/kitex_gen/base"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *CreateReviewRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CreateReviewRequest[number], err)
}

func (x *CreateReviewRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.OrderId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.ItemScore, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.ServiceScore, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.ExpressScore, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.Content, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.PicInfo, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.VideoInfo, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	x.Anonymous, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *CreateReviewResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 255:
		offset, err = x.fastReadField255(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CreateReviewResponse[number], err)
}

func (x *CreateReviewResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ReviewId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateReviewResponse) fastReadField255(buf []byte, _type int8) (offset int, err error) {
	var v base.BaseResp
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.BaseResp = &v
	return offset, nil
}

func (x *CreateReviewRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	return offset
}

func (x *CreateReviewRequest) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *CreateReviewRequest) fastWriteField2(buf []byte) (offset int) {
	if x.OrderId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetOrderId())
	return offset
}

func (x *CreateReviewRequest) fastWriteField3(buf []byte) (offset int) {
	if x.ItemScore == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 3, x.GetItemScore())
	return offset
}

func (x *CreateReviewRequest) fastWriteField4(buf []byte) (offset int) {
	if x.ServiceScore == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 4, x.GetServiceScore())
	return offset
}

func (x *CreateReviewRequest) fastWriteField5(buf []byte) (offset int) {
	if x.ExpressScore == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 5, x.GetExpressScore())
	return offset
}

func (x *CreateReviewRequest) fastWriteField6(buf []byte) (offset int) {
	if x.Content == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 6, x.GetContent())
	return offset
}

func (x *CreateReviewRequest) fastWriteField7(buf []byte) (offset int) {
	if x.PicInfo == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 7, x.GetPicInfo())
	return offset
}

func (x *CreateReviewRequest) fastWriteField8(buf []byte) (offset int) {
	if x.VideoInfo == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 8, x.GetVideoInfo())
	return offset
}

func (x *CreateReviewRequest) fastWriteField9(buf []byte) (offset int) {
	if !x.Anonymous {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 9, x.GetAnonymous())
	return offset
}

func (x *CreateReviewResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField255(buf[offset:])
	return offset
}

func (x *CreateReviewResponse) fastWriteField1(buf []byte) (offset int) {
	if x.ReviewId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetReviewId())
	return offset
}

func (x *CreateReviewResponse) fastWriteField255(buf []byte) (offset int) {
	if x.BaseResp == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 255, x.GetBaseResp())
	return offset
}

func (x *CreateReviewRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	return n
}

func (x *CreateReviewRequest) sizeField1() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetUserId())
	return n
}

func (x *CreateReviewRequest) sizeField2() (n int) {
	if x.OrderId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetOrderId())
	return n
}

func (x *CreateReviewRequest) sizeField3() (n int) {
	if x.ItemScore == 0 {
		return n
	}
	n += fastpb.SizeInt32(3, x.GetItemScore())
	return n
}

func (x *CreateReviewRequest) sizeField4() (n int) {
	if x.ServiceScore == 0 {
		return n
	}
	n += fastpb.SizeInt32(4, x.GetServiceScore())
	return n
}

func (x *CreateReviewRequest) sizeField5() (n int) {
	if x.ExpressScore == 0 {
		return n
	}
	n += fastpb.SizeInt32(5, x.GetExpressScore())
	return n
}

func (x *CreateReviewRequest) sizeField6() (n int) {
	if x.Content == "" {
		return n
	}
	n += fastpb.SizeString(6, x.GetContent())
	return n
}

func (x *CreateReviewRequest) sizeField7() (n int) {
	if x.PicInfo == "" {
		return n
	}
	n += fastpb.SizeString(7, x.GetPicInfo())
	return n
}

func (x *CreateReviewRequest) sizeField8() (n int) {
	if x.VideoInfo == "" {
		return n
	}
	n += fastpb.SizeString(8, x.GetVideoInfo())
	return n
}

func (x *CreateReviewRequest) sizeField9() (n int) {
	if !x.Anonymous {
		return n
	}
	n += fastpb.SizeBool(9, x.GetAnonymous())
	return n
}

func (x *CreateReviewResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField255()
	return n
}

func (x *CreateReviewResponse) sizeField1() (n int) {
	if x.ReviewId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetReviewId())
	return n
}

func (x *CreateReviewResponse) sizeField255() (n int) {
	if x.BaseResp == nil {
		return n
	}
	n += fastpb.SizeMessage(255, x.GetBaseResp())
	return n
}

var fieldIDToName_CreateReviewRequest = map[int32]string{
	1: "UserId",
	2: "OrderId",
	3: "ItemScore",
	4: "ServiceScore",
	5: "ExpressScore",
	6: "Content",
	7: "PicInfo",
	8: "VideoInfo",
	9: "Anonymous",
}

var fieldIDToName_CreateReviewResponse = map[int32]string{
	1:   "ReviewId",
	255: "BaseResp",
}

var _ = api.File_api_proto
var _ = base.File_base_proto
