// Code generated by hertz generator.

package gateway

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appealMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _auditappealMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appealreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _auditreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _replyreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __7buser_id_7dMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listreviewbyuseridMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _skuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __7bsku_id_7dMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listreviewbyskuidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _spuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __7bspu_id_7dMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listreviewbyspuidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _storeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __7bstore_id_7dMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listreviewbystoreidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _store_idMw() []app.HandlerFunc {
	// your code...
	return nil
}
