// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package review

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
	api "github.com/yzc/orange-review/rpc_gen/kitex_gen/api"
	base "github.com/yzc/orange-review/rpc_gen/kitex_gen/base"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *CreateReviewRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 10:
		offset, err = x.fastReadField10(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 11:
		offset, err = x.fastReadField11(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 12:
		offset, err = x.fastReadField12(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CreateReviewRequest[number], err)
}

func (x *CreateReviewRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.OrderId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.ItemScore, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.ServiceScore, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.ExpressScore, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.Content, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.PicInfo, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.VideoInfo, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	x.Anonymous, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField10(buf []byte, _type int8) (offset int, err error) {
	x.SkuId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField11(buf []byte, _type int8) (offset int, err error) {
	x.SpuId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) fastReadField12(buf []byte, _type int8) (offset int, err error) {
	x.StoreId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateReviewResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 255:
		offset, err = x.fastReadField255(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CreateReviewResponse[number], err)
}

func (x *CreateReviewResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ReviewId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateReviewResponse) fastReadField255(buf []byte, _type int8) (offset int, err error) {
	var v base.BaseResp
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.BaseResp = &v
	return offset, nil
}

func (x *ListReviewByStoreIDReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListReviewByStoreIDReq[number], err)
}

func (x *ListReviewByStoreIDReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.StoreID, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListReviewByStoreIDReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Page, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *ListReviewByStoreIDReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.PageSize, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *ListReviewByStoreIDResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 255:
		offset, err = x.fastReadField255(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListReviewByStoreIDResp[number], err)
}

func (x *ListReviewByStoreIDResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v ReviewInfo
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.List = append(x.List, &v)
	return offset, nil
}

func (x *ListReviewByStoreIDResp) fastReadField255(buf []byte, _type int8) (offset int, err error) {
	var v base.BaseResp
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.BaseResp = &v
	return offset, nil
}

func (x *ListReviewBySpuIDReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListReviewBySpuIDReq[number], err)
}

func (x *ListReviewBySpuIDReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.SpuID, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListReviewBySpuIDReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Page, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *ListReviewBySpuIDReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.PageSize, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *ListReviewBySpuIDResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 255:
		offset, err = x.fastReadField255(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListReviewBySpuIDResp[number], err)
}

func (x *ListReviewBySpuIDResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v ReviewInfo
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.List = append(x.List, &v)
	return offset, nil
}

func (x *ListReviewBySpuIDResp) fastReadField255(buf []byte, _type int8) (offset int, err error) {
	var v base.BaseResp
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.BaseResp = &v
	return offset, nil
}

func (x *ListReviewBySkuIDReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListReviewBySkuIDReq[number], err)
}

func (x *ListReviewBySkuIDReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.SkuID, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListReviewBySkuIDReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Page, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *ListReviewBySkuIDReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.PageSize, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *ListReviewBySkuIDResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 255:
		offset, err = x.fastReadField255(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListReviewBySkuIDResp[number], err)
}

func (x *ListReviewBySkuIDResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v ReviewInfo
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.List = append(x.List, &v)
	return offset, nil
}

func (x *ListReviewBySkuIDResp) fastReadField255(buf []byte, _type int8) (offset int, err error) {
	var v base.BaseResp
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.BaseResp = &v
	return offset, nil
}

func (x *ReviewInfo) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 10:
		offset, err = x.fastReadField10(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ReviewInfo[number], err)
}

func (x *ReviewInfo) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ReviewID, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ReviewInfo) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserID, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ReviewInfo) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.OrderID, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ReviewInfo) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Score, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *ReviewInfo) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.ServiceScore, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *ReviewInfo) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.ExpressScore, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *ReviewInfo) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.Content, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ReviewInfo) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.PicInfo, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ReviewInfo) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	x.VideoInfo, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ReviewInfo) fastReadField10(buf []byte, _type int8) (offset int, err error) {
	x.Status, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *CreateReviewRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	offset += x.fastWriteField10(buf[offset:])
	offset += x.fastWriteField11(buf[offset:])
	offset += x.fastWriteField12(buf[offset:])
	return offset
}

func (x *CreateReviewRequest) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *CreateReviewRequest) fastWriteField2(buf []byte) (offset int) {
	if x.OrderId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetOrderId())
	return offset
}

func (x *CreateReviewRequest) fastWriteField3(buf []byte) (offset int) {
	if x.ItemScore == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 3, x.GetItemScore())
	return offset
}

func (x *CreateReviewRequest) fastWriteField4(buf []byte) (offset int) {
	if x.ServiceScore == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 4, x.GetServiceScore())
	return offset
}

func (x *CreateReviewRequest) fastWriteField5(buf []byte) (offset int) {
	if x.ExpressScore == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 5, x.GetExpressScore())
	return offset
}

func (x *CreateReviewRequest) fastWriteField6(buf []byte) (offset int) {
	if x.Content == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 6, x.GetContent())
	return offset
}

func (x *CreateReviewRequest) fastWriteField7(buf []byte) (offset int) {
	if x.PicInfo == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 7, x.GetPicInfo())
	return offset
}

func (x *CreateReviewRequest) fastWriteField8(buf []byte) (offset int) {
	if x.VideoInfo == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 8, x.GetVideoInfo())
	return offset
}

func (x *CreateReviewRequest) fastWriteField9(buf []byte) (offset int) {
	if !x.Anonymous {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 9, x.GetAnonymous())
	return offset
}

func (x *CreateReviewRequest) fastWriteField10(buf []byte) (offset int) {
	if x.SkuId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 10, x.GetSkuId())
	return offset
}

func (x *CreateReviewRequest) fastWriteField11(buf []byte) (offset int) {
	if x.SpuId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 11, x.GetSpuId())
	return offset
}

func (x *CreateReviewRequest) fastWriteField12(buf []byte) (offset int) {
	if x.StoreId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 12, x.GetStoreId())
	return offset
}

func (x *CreateReviewResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField255(buf[offset:])
	return offset
}

func (x *CreateReviewResponse) fastWriteField1(buf []byte) (offset int) {
	if x.ReviewId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetReviewId())
	return offset
}

func (x *CreateReviewResponse) fastWriteField255(buf []byte) (offset int) {
	if x.BaseResp == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 255, x.GetBaseResp())
	return offset
}

func (x *ListReviewByStoreIDReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ListReviewByStoreIDReq) fastWriteField1(buf []byte) (offset int) {
	if x.StoreID == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetStoreID())
	return offset
}

func (x *ListReviewByStoreIDReq) fastWriteField2(buf []byte) (offset int) {
	if x.Page == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 2, x.GetPage())
	return offset
}

func (x *ListReviewByStoreIDReq) fastWriteField3(buf []byte) (offset int) {
	if x.PageSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 3, x.GetPageSize())
	return offset
}

func (x *ListReviewByStoreIDResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField255(buf[offset:])
	return offset
}

func (x *ListReviewByStoreIDResp) fastWriteField1(buf []byte) (offset int) {
	if x.List == nil {
		return offset
	}
	for i := range x.GetList() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetList()[i])
	}
	return offset
}

func (x *ListReviewByStoreIDResp) fastWriteField255(buf []byte) (offset int) {
	if x.BaseResp == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 255, x.GetBaseResp())
	return offset
}

func (x *ListReviewBySpuIDReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ListReviewBySpuIDReq) fastWriteField1(buf []byte) (offset int) {
	if x.SpuID == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetSpuID())
	return offset
}

func (x *ListReviewBySpuIDReq) fastWriteField2(buf []byte) (offset int) {
	if x.Page == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 2, x.GetPage())
	return offset
}

func (x *ListReviewBySpuIDReq) fastWriteField3(buf []byte) (offset int) {
	if x.PageSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 3, x.GetPageSize())
	return offset
}

func (x *ListReviewBySpuIDResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField255(buf[offset:])
	return offset
}

func (x *ListReviewBySpuIDResp) fastWriteField1(buf []byte) (offset int) {
	if x.List == nil {
		return offset
	}
	for i := range x.GetList() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetList()[i])
	}
	return offset
}

func (x *ListReviewBySpuIDResp) fastWriteField255(buf []byte) (offset int) {
	if x.BaseResp == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 255, x.GetBaseResp())
	return offset
}

func (x *ListReviewBySkuIDReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ListReviewBySkuIDReq) fastWriteField1(buf []byte) (offset int) {
	if x.SkuID == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetSkuID())
	return offset
}

func (x *ListReviewBySkuIDReq) fastWriteField2(buf []byte) (offset int) {
	if x.Page == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 2, x.GetPage())
	return offset
}

func (x *ListReviewBySkuIDReq) fastWriteField3(buf []byte) (offset int) {
	if x.PageSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 3, x.GetPageSize())
	return offset
}

func (x *ListReviewBySkuIDResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField255(buf[offset:])
	return offset
}

func (x *ListReviewBySkuIDResp) fastWriteField1(buf []byte) (offset int) {
	if x.List == nil {
		return offset
	}
	for i := range x.GetList() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetList()[i])
	}
	return offset
}

func (x *ListReviewBySkuIDResp) fastWriteField255(buf []byte) (offset int) {
	if x.BaseResp == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 255, x.GetBaseResp())
	return offset
}

func (x *ReviewInfo) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	offset += x.fastWriteField10(buf[offset:])
	return offset
}

func (x *ReviewInfo) fastWriteField1(buf []byte) (offset int) {
	if x.ReviewID == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetReviewID())
	return offset
}

func (x *ReviewInfo) fastWriteField2(buf []byte) (offset int) {
	if x.UserID == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetUserID())
	return offset
}

func (x *ReviewInfo) fastWriteField3(buf []byte) (offset int) {
	if x.OrderID == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 3, x.GetOrderID())
	return offset
}

func (x *ReviewInfo) fastWriteField4(buf []byte) (offset int) {
	if x.Score == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 4, x.GetScore())
	return offset
}

func (x *ReviewInfo) fastWriteField5(buf []byte) (offset int) {
	if x.ServiceScore == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 5, x.GetServiceScore())
	return offset
}

func (x *ReviewInfo) fastWriteField6(buf []byte) (offset int) {
	if x.ExpressScore == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 6, x.GetExpressScore())
	return offset
}

func (x *ReviewInfo) fastWriteField7(buf []byte) (offset int) {
	if x.Content == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 7, x.GetContent())
	return offset
}

func (x *ReviewInfo) fastWriteField8(buf []byte) (offset int) {
	if x.PicInfo == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 8, x.GetPicInfo())
	return offset
}

func (x *ReviewInfo) fastWriteField9(buf []byte) (offset int) {
	if x.VideoInfo == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 9, x.GetVideoInfo())
	return offset
}

func (x *ReviewInfo) fastWriteField10(buf []byte) (offset int) {
	if x.Status == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 10, x.GetStatus())
	return offset
}

func (x *CreateReviewRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	n += x.sizeField10()
	n += x.sizeField11()
	n += x.sizeField12()
	return n
}

func (x *CreateReviewRequest) sizeField1() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetUserId())
	return n
}

func (x *CreateReviewRequest) sizeField2() (n int) {
	if x.OrderId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetOrderId())
	return n
}

func (x *CreateReviewRequest) sizeField3() (n int) {
	if x.ItemScore == 0 {
		return n
	}
	n += fastpb.SizeInt32(3, x.GetItemScore())
	return n
}

func (x *CreateReviewRequest) sizeField4() (n int) {
	if x.ServiceScore == 0 {
		return n
	}
	n += fastpb.SizeInt32(4, x.GetServiceScore())
	return n
}

func (x *CreateReviewRequest) sizeField5() (n int) {
	if x.ExpressScore == 0 {
		return n
	}
	n += fastpb.SizeInt32(5, x.GetExpressScore())
	return n
}

func (x *CreateReviewRequest) sizeField6() (n int) {
	if x.Content == "" {
		return n
	}
	n += fastpb.SizeString(6, x.GetContent())
	return n
}

func (x *CreateReviewRequest) sizeField7() (n int) {
	if x.PicInfo == "" {
		return n
	}
	n += fastpb.SizeString(7, x.GetPicInfo())
	return n
}

func (x *CreateReviewRequest) sizeField8() (n int) {
	if x.VideoInfo == "" {
		return n
	}
	n += fastpb.SizeString(8, x.GetVideoInfo())
	return n
}

func (x *CreateReviewRequest) sizeField9() (n int) {
	if !x.Anonymous {
		return n
	}
	n += fastpb.SizeBool(9, x.GetAnonymous())
	return n
}

func (x *CreateReviewRequest) sizeField10() (n int) {
	if x.SkuId == 0 {
		return n
	}
	n += fastpb.SizeInt64(10, x.GetSkuId())
	return n
}

func (x *CreateReviewRequest) sizeField11() (n int) {
	if x.SpuId == 0 {
		return n
	}
	n += fastpb.SizeInt64(11, x.GetSpuId())
	return n
}

func (x *CreateReviewRequest) sizeField12() (n int) {
	if x.StoreId == 0 {
		return n
	}
	n += fastpb.SizeInt64(12, x.GetStoreId())
	return n
}

func (x *CreateReviewResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField255()
	return n
}

func (x *CreateReviewResponse) sizeField1() (n int) {
	if x.ReviewId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetReviewId())
	return n
}

func (x *CreateReviewResponse) sizeField255() (n int) {
	if x.BaseResp == nil {
		return n
	}
	n += fastpb.SizeMessage(255, x.GetBaseResp())
	return n
}

func (x *ListReviewByStoreIDReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ListReviewByStoreIDReq) sizeField1() (n int) {
	if x.StoreID == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetStoreID())
	return n
}

func (x *ListReviewByStoreIDReq) sizeField2() (n int) {
	if x.Page == 0 {
		return n
	}
	n += fastpb.SizeInt32(2, x.GetPage())
	return n
}

func (x *ListReviewByStoreIDReq) sizeField3() (n int) {
	if x.PageSize == 0 {
		return n
	}
	n += fastpb.SizeInt32(3, x.GetPageSize())
	return n
}

func (x *ListReviewByStoreIDResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField255()
	return n
}

func (x *ListReviewByStoreIDResp) sizeField1() (n int) {
	if x.List == nil {
		return n
	}
	for i := range x.GetList() {
		n += fastpb.SizeMessage(1, x.GetList()[i])
	}
	return n
}

func (x *ListReviewByStoreIDResp) sizeField255() (n int) {
	if x.BaseResp == nil {
		return n
	}
	n += fastpb.SizeMessage(255, x.GetBaseResp())
	return n
}

func (x *ListReviewBySpuIDReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ListReviewBySpuIDReq) sizeField1() (n int) {
	if x.SpuID == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetSpuID())
	return n
}

func (x *ListReviewBySpuIDReq) sizeField2() (n int) {
	if x.Page == 0 {
		return n
	}
	n += fastpb.SizeInt32(2, x.GetPage())
	return n
}

func (x *ListReviewBySpuIDReq) sizeField3() (n int) {
	if x.PageSize == 0 {
		return n
	}
	n += fastpb.SizeInt32(3, x.GetPageSize())
	return n
}

func (x *ListReviewBySpuIDResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField255()
	return n
}

func (x *ListReviewBySpuIDResp) sizeField1() (n int) {
	if x.List == nil {
		return n
	}
	for i := range x.GetList() {
		n += fastpb.SizeMessage(1, x.GetList()[i])
	}
	return n
}

func (x *ListReviewBySpuIDResp) sizeField255() (n int) {
	if x.BaseResp == nil {
		return n
	}
	n += fastpb.SizeMessage(255, x.GetBaseResp())
	return n
}

func (x *ListReviewBySkuIDReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ListReviewBySkuIDReq) sizeField1() (n int) {
	if x.SkuID == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetSkuID())
	return n
}

func (x *ListReviewBySkuIDReq) sizeField2() (n int) {
	if x.Page == 0 {
		return n
	}
	n += fastpb.SizeInt32(2, x.GetPage())
	return n
}

func (x *ListReviewBySkuIDReq) sizeField3() (n int) {
	if x.PageSize == 0 {
		return n
	}
	n += fastpb.SizeInt32(3, x.GetPageSize())
	return n
}

func (x *ListReviewBySkuIDResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField255()
	return n
}

func (x *ListReviewBySkuIDResp) sizeField1() (n int) {
	if x.List == nil {
		return n
	}
	for i := range x.GetList() {
		n += fastpb.SizeMessage(1, x.GetList()[i])
	}
	return n
}

func (x *ListReviewBySkuIDResp) sizeField255() (n int) {
	if x.BaseResp == nil {
		return n
	}
	n += fastpb.SizeMessage(255, x.GetBaseResp())
	return n
}

func (x *ReviewInfo) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	n += x.sizeField10()
	return n
}

func (x *ReviewInfo) sizeField1() (n int) {
	if x.ReviewID == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetReviewID())
	return n
}

func (x *ReviewInfo) sizeField2() (n int) {
	if x.UserID == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetUserID())
	return n
}

func (x *ReviewInfo) sizeField3() (n int) {
	if x.OrderID == 0 {
		return n
	}
	n += fastpb.SizeInt64(3, x.GetOrderID())
	return n
}

func (x *ReviewInfo) sizeField4() (n int) {
	if x.Score == 0 {
		return n
	}
	n += fastpb.SizeInt32(4, x.GetScore())
	return n
}

func (x *ReviewInfo) sizeField5() (n int) {
	if x.ServiceScore == 0 {
		return n
	}
	n += fastpb.SizeInt32(5, x.GetServiceScore())
	return n
}

func (x *ReviewInfo) sizeField6() (n int) {
	if x.ExpressScore == 0 {
		return n
	}
	n += fastpb.SizeInt32(6, x.GetExpressScore())
	return n
}

func (x *ReviewInfo) sizeField7() (n int) {
	if x.Content == "" {
		return n
	}
	n += fastpb.SizeString(7, x.GetContent())
	return n
}

func (x *ReviewInfo) sizeField8() (n int) {
	if x.PicInfo == "" {
		return n
	}
	n += fastpb.SizeString(8, x.GetPicInfo())
	return n
}

func (x *ReviewInfo) sizeField9() (n int) {
	if x.VideoInfo == "" {
		return n
	}
	n += fastpb.SizeString(9, x.GetVideoInfo())
	return n
}

func (x *ReviewInfo) sizeField10() (n int) {
	if x.Status == 0 {
		return n
	}
	n += fastpb.SizeInt32(10, x.GetStatus())
	return n
}

var fieldIDToName_CreateReviewRequest = map[int32]string{
	1:  "UserId",
	2:  "OrderId",
	3:  "ItemScore",
	4:  "ServiceScore",
	5:  "ExpressScore",
	6:  "Content",
	7:  "PicInfo",
	8:  "VideoInfo",
	9:  "Anonymous",
	10: "SkuId",
	11: "SpuId",
	12: "StoreId",
}

var fieldIDToName_CreateReviewResponse = map[int32]string{
	1:   "ReviewId",
	255: "BaseResp",
}

var fieldIDToName_ListReviewByStoreIDReq = map[int32]string{
	1: "StoreID",
	2: "Page",
	3: "PageSize",
}

var fieldIDToName_ListReviewByStoreIDResp = map[int32]string{
	1:   "List",
	255: "BaseResp",
}

var fieldIDToName_ListReviewBySpuIDReq = map[int32]string{
	1: "SpuID",
	2: "Page",
	3: "PageSize",
}

var fieldIDToName_ListReviewBySpuIDResp = map[int32]string{
	1:   "List",
	255: "BaseResp",
}

var fieldIDToName_ListReviewBySkuIDReq = map[int32]string{
	1: "SkuID",
	2: "Page",
	3: "PageSize",
}

var fieldIDToName_ListReviewBySkuIDResp = map[int32]string{
	1:   "List",
	255: "BaseResp",
}

var fieldIDToName_ReviewInfo = map[int32]string{
	1:  "ReviewID",
	2:  "UserID",
	3:  "OrderID",
	4:  "Score",
	5:  "ServiceScore",
	6:  "ExpressScore",
	7:  "Content",
	8:  "PicInfo",
	9:  "VideoInfo",
	10: "Status",
}

var _ = api.File_api_proto
var _ = base.File_base_proto
