// Code generated by Kitex v0.9.1. DO NOT EDIT.

package reviewservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	review "github.com/yzc/orange-review/app/review_server/kitex_gen/review"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateReview(ctx context.Context, Req *review.CreateReviewRequest, callOptions ...callopt.Option) (r *review.CreateReviewResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kReviewServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kReviewServiceClient struct {
	*kClient
}

func (p *kReviewServiceClient) CreateReview(ctx context.Context, Req *review.CreateReviewRequest, callOptions ...callopt.Option) (r *review.CreateReviewResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateReview(ctx, Req)
}
