// Code generated by Kitex v0.9.1. DO NOT EDIT.

package reviewservice

import (
	server "github.com/cloudwego/kitex/server"
	review "github.com/yzc/orange-review/app/review_server/kitex_gen/review"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler review.ReviewService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
