// Code generated by Kitex v0.9.1. DO NOT EDIT.

package reviewservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	review "github.com/yzc/orange-review/app/review_server/kitex_gen/review"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateReview": kitex.NewMethodInfo(
		createReviewHandler,
		newCreateReviewArgs,
		newCreateReviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	reviewServiceServiceInfo                = NewServiceInfo()
	reviewServiceServiceInfoForClient       = NewServiceInfoForClient()
	reviewServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return reviewServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return reviewServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return reviewServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ReviewService"
	handlerType := (*review.ReviewService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "review",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func createReviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(review.CreateReviewRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(review.ReviewService).CreateReview(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateReviewArgs:
		success, err := handler.(review.ReviewService).CreateReview(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateReviewResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateReviewArgs() interface{} {
	return &CreateReviewArgs{}
}

func newCreateReviewResult() interface{} {
	return &CreateReviewResult{}
}

type CreateReviewArgs struct {
	Req *review.CreateReviewRequest
}

func (p *CreateReviewArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(review.CreateReviewRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CreateReviewArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CreateReviewArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CreateReviewArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateReviewArgs) Unmarshal(in []byte) error {
	msg := new(review.CreateReviewRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateReviewArgs_Req_DEFAULT *review.CreateReviewRequest

func (p *CreateReviewArgs) GetReq() *review.CreateReviewRequest {
	if !p.IsSetReq() {
		return CreateReviewArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateReviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateReviewArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateReviewResult struct {
	Success *review.CreateReviewResponse
}

var CreateReviewResult_Success_DEFAULT *review.CreateReviewResponse

func (p *CreateReviewResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(review.CreateReviewResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CreateReviewResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CreateReviewResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CreateReviewResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateReviewResult) Unmarshal(in []byte) error {
	msg := new(review.CreateReviewResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateReviewResult) GetSuccess() *review.CreateReviewResponse {
	if !p.IsSetSuccess() {
		return CreateReviewResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateReviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*review.CreateReviewResponse)
}

func (p *CreateReviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateReviewResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateReview(ctx context.Context, Req *review.CreateReviewRequest) (r *review.CreateReviewResponse, err error) {
	var _args CreateReviewArgs
	_args.Req = Req
	var _result CreateReviewResult
	if err = p.c.Call(ctx, "CreateReview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
