// Code generated by Kitex v0.9.1. DO NOT EDIT.
package reviewservice

import (
	server "github.com/cloudwego/kitex/server"
	review "github.com/yzc/orange-review/app/review_server/kitex_gen/review"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler review.ReviewService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler review.ReviewService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
