// Code generated by Kitex v0.9.1. DO NOT EDIT.

package idgenerateservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	generator "github.com/yzc/orange-review/app/id_generator/kitex_gen/generator"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GenID(ctx context.Context, Req *generator.GenIDRequest, callOptions ...callopt.Option) (r *generator.GenIDResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kIDGenerateServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kIDGenerateServiceClient struct {
	*kClient
}

func (p *kIDGenerateServiceClient) GenID(ctx context.Context, Req *generator.GenIDRequest, callOptions ...callopt.Option) (r *generator.GenIDResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenID(ctx, Req)
}
