// Code generated by Kitex v0.9.1. DO NOT EDIT.

package idgenerateservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	generator "github.com/yzc/orange-review/app/id_generator/kitex_gen/generator"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GenID": kitex.NewMethodInfo(
		genIDHandler,
		newGenIDArgs,
		newGenIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	iDGenerateServiceServiceInfo                = NewServiceInfo()
	iDGenerateServiceServiceInfoForClient       = NewServiceInfoForClient()
	iDGenerateServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return iDGenerateServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return iDGenerateServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return iDGenerateServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "IDGenerateService"
	handlerType := (*generator.IDGenerateService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "generator",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func genIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(generator.GenIDRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(generator.IDGenerateService).GenID(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GenIDArgs:
		success, err := handler.(generator.IDGenerateService).GenID(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GenIDResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGenIDArgs() interface{} {
	return &GenIDArgs{}
}

func newGenIDResult() interface{} {
	return &GenIDResult{}
}

type GenIDArgs struct {
	Req *generator.GenIDRequest
}

func (p *GenIDArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(generator.GenIDRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GenIDArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GenIDArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GenIDArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenIDArgs) Unmarshal(in []byte) error {
	msg := new(generator.GenIDRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenIDArgs_Req_DEFAULT *generator.GenIDRequest

func (p *GenIDArgs) GetReq() *generator.GenIDRequest {
	if !p.IsSetReq() {
		return GenIDArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenIDArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenIDResult struct {
	Success *generator.GenIDResponse
}

var GenIDResult_Success_DEFAULT *generator.GenIDResponse

func (p *GenIDResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(generator.GenIDResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GenIDResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GenIDResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GenIDResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenIDResult) Unmarshal(in []byte) error {
	msg := new(generator.GenIDResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenIDResult) GetSuccess() *generator.GenIDResponse {
	if !p.IsSetSuccess() {
		return GenIDResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*generator.GenIDResponse)
}

func (p *GenIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenIDResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GenID(ctx context.Context, Req *generator.GenIDRequest) (r *generator.GenIDResponse, err error) {
	var _args GenIDArgs
	_args.Req = Req
	var _result GenIDResult
	if err = p.c.Call(ctx, "GenID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
