// Code generated by Kitex v0.9.1. DO NOT EDIT.
package idgenerateservice

import (
	server "github.com/cloudwego/kitex/server"
	generator "github.com/yzc/orange-review/app/id_generator/kitex_gen/generator"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler generator.IDGenerateService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler generator.IDGenerateService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
